### ISSUE TITLE
Another issue associated with points in the notebook 

### ISSUE THREAD

**Issue by lwasser** [earthlab/autograding-notebooks#8]
@jlpalomino  i really am not sure exactly what this means: look at error of partial credit larger than cell point possible with hidden tests:  https://github.com/jlpalomino/autograding-notebooks/blob/master/notebooks/bootcamp-test-assignment.ipynb

can you kindly add some clarification for @kcranston so we can track this issue?

**Comment by jlpalomino** [comment]
@lwasser Detail added here for our reference (@kcranston also has the information via Slack from yesterday's session).  The issue is that when the last test that checks the dataframe in the [test assignment](https://github.com/jlpalomino/autograding-notebooks/blob/master/notebooks/bootcamp-test-assignment.ipynb) is put into its own cell as a hidden test, the notebook results in a error during the local validation step by the instructor:
```
[ValidateApp | ERROR] Traceback (most recent call last):
      File "/home/jpalomino/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/nbgrader/apps/validateapp.py", line 71, in start
        validator.validate_and_print(filename)
      File "/home/jpalomino/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/nbgrader/validator.py", line 340, in validate_and_print
        results = self.validate(filename)
      File "/home/jpalomino/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/nbgrader/validator.py", line 313, in validate
        passed = self._get_passed_cells(nb)
      File "/home/jpalomino/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/nbgrader/validator.py", line 271, in _get_passed_cells
        score, max_score = utils.determine_grade(cell, self.log)
      File "/home/jpalomino/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/nbgrader/utils.py", line 119, in determine_grade
        partial_grade = get_partial_grade(output, max_points, log)
      File "/home/jpalomino/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/nbgrader/utils.py", line 86, in get_partial_grade
        raise ValueError("partial credit cannot be greater than maximum points for cell")
    ValueError: partial credit cannot be greater than maximum points for cell
```
This error appears to be saying that somehow the partial credit for the cell is resolving into more points than the 6 max points that has been allotted to the cell. It is possibly related to issue #7, which indicated that the number of points for each cell was not being accurately maintained.

**Comment by kcranston** [comment]
The issue is that in the hidden test cell, when you call 

```
results.append(data_test)
output_results(results)
```
you are appending the results to a non-empty array (`results` is defined in the previous cell). So, when you output the results, it includes points from this cell and the previous cell, which is more than the allowed points for the cell. 

Solution: either reset the results array with `results = []` and the top of the cell, or use a different variable name.
